// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://burrhjwpudmsjbnrisgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1cnJoandwdWRtc2pibnJpc2dkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NjMxMzQsImV4cCI6MjA1OTAzOTEzNH0.2xK3pSN_ZvjiNyNbkJRXJMKrl_jwPZXGaBiEj6d0whk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);